name: Pull request linter

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  enforce-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: pr-number
        shell: bash
        run: |
          if [ ${{ github.event_name }} == 'pull_request' ]
          then
            echo "Event type: pull request"
            pr=${{ github.event.number }}
          elif [ ${{ github.event_name }} == 'merge_group' ]
          then
            echo "Event type: merge queue"
            pr=$(echo ${{ github.event.merge_group.head_ref }} | grep -Eo "queue/main/pr-[0-9]+" | cut -d '-' -f2)
          else
            echo "Event type: unknown or unexpected"
          fi

          # Validate PR number
          if [[ ! "${pr}" =~ ^[0-9]+$ ]]; then
            echo "PR number format incorrect: ${pr}"
            exit 1
          fi

          # Output PR number
          echo "Summary ---"
          echo -e "\tPR: ${pr}"
          echo "pr=${pr}" >> $GITHUB_OUTPUT

      - name: Get release-drafter config
        id: current-labels
        run: |
          echo "labels=$(yq -r '[.categories[].labels, .exclude-labels] | flatten[]' .github/release-drafter.yml | tr '\n' ',')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Check PR labels
        id: check-labels
        run: |
          PR_LABELS=$(gh pr view ${{ steps.pr-number.outputs.pr }} --json labels -q '.labels[].name')
          echo $PR_LABELS
          MATCH_FOUND=0

          for label in $PR_LABELS; do
            if [[ "${{ steps.current-labels.outputs.labels }}" =~ "$label" ]]; then
              MATCH_FOUND=1
              break
            fi
          done

          if [[ ! $MATCH_FOUND -eq 1 ]]; then
            echo "No matching labels found. Must have one of: ${{ steps.current-labels.outputs.labels }}"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
